### PR TITLE
Refactor and rename files in preparation for parser

### PR DESCRIPTION
**Pull request by alexschneider**
Changes:
1. Move all example programs from the scanner to the example directory (they apply to all parts of our compiler, not just the scanner). 
2. Add line numbers to the scanner to aid parser's error checking. 
3. Add entry point to our compiler (teascript.coffee). Pretty minimal ATM.

### CODE REVIEW

**Comment by rachelriv** [comment]
I was thinking that we should create a `scanner` directory and then put the `scanner.coffee` and all the `line_scanner` stuff in that directory. What do you think?

All of the changes LGTM. :tea:

**Comment by alexschneider** [comment]
I'm not sure why coveralls is complaining, because it's showing 100% coverage for the as/reorg... branch, but the PR is showing 96.09. As a result, I'm inclined to just say that there must be a mistake, and if the coverage is still low when it hits master, I'll fix it. 

@rachelriv please review and merge.

**Comment by juansc** [comment]
I'm fine with creating a `scanner` directory.

**Comment by alexschneider** [comment]
RE the scanner directory - I think it's fine to have one top level scanner.coffee, parser.coffee, etc, because that's how @rtoal did it with Iki. If you think it would be more clear to move the scanner.coffee into a scanner directory, that's fine with me too.

**Comment by rachelriv** [comment]
When I talked to Dr. Toal about it before class on Thursday he said that having a separate directory would be fine. He said that he just kept so much at top level for iki since it is a fairly simple example.

**Comment by alexschneider** [comment]
Fine by me. I've gotta go somewhere in a few minutes, so I can do this when I get back later tonight, or someone else can do it now.

**Comment by rachelriv** [comment]
I might do it in a separate PR. I'll also try to figure out why coveralls is complaining.

Have a good night!

**Comment by alexschneider** [comment]
Don't worry too much about coveralls. We'll figure it out later.

**Comment by alexschneider** [comment]
W00T, COVERAGE FIXED!

**Comment by rachelriv** [comment]
Looks good.

**Pull request merged**
