### PR TITLE
Created two scanner tests.

### PR DESCRIPTION
**Pull request by juansc**
Created two scanner tests.

### CODE REVIEW

**Comment by alexschneider** [comment]
This probably isn't quite yet ready to merge, I'd feel more comfortable if we have Mocha unit tests for this (shouldn't be that difficult to write). If you don't know how, I can show you tomorrow.

**Comment by juansc** [comment]
Will you be in the lab before 9:25?

**Comment by alexschneider** [comment]
Yes, I usually get in at 8-8:30

**Comment by juansc** [comment]
Cool see you then.

**Comment by rachelriv** [comment]
@juansc Check out the most recent PR https://github.com/alexschneider/teascript/pull/12. You should just be able to add your sample programs into the `test/scanner/input_programs` directory as well as add expected output tokens to the `test/scanner/output_tokens` module. You can then just add a couple more tests into the `test/scanner/scanner_spec`

**Comment by rachelriv** [comment]
@juansc 
UPDATE: You should be able to just pull the master and then add your tests.

**Pull request closed without merging**
