### PR TITLE
Fix errors and styling

### PR DESCRIPTION
**Pull request by alexschneider**
@rachelriv: I'm a bit confused as to why we're using sinon, but it's causing Travis to error out, so I removed it and sinon-chai. It doesn't look like it affected the tests at all. Let me know if there's any reason we need it. 

Everyone else, please review and merge.

### CODE REVIEW

**Comment by rachelriv** [comment]
@alexschneider I am using sinon in the `line_scanner_spec` to test our control flow. For example, if a line is completely empty, then none of the extraction methods should be called.

**Comment by alexschneider** [comment]
Do you mind resolving the sinon-chai errors then? I took a crack at it, but I'm unsure what versions work well. See https://travis-ci.org/alexschneider/teascript/builds/50534243.

I'll revert my changes to line_scanner_spec.

**Comment by rachelriv** [comment]
Yes, I'll take a look at it! If I am able to fix it, could you please add all of the control-flow tests back into this branch?

**Comment by alexschneider** [comment]
I reverted all my changes to sinon except for the NPM change. Feel free to push directly to this branch when you figure it out.

**Comment by rachelriv** [comment]
@alexschneider sinon-chai is not compatible with the most recent release of chai. https://github.com/domenic/sinon-chai/issues/58 

I fixed this on the rr/add-npm-test branch. We should consider using shrinkwrap to lock down the versions of our dependencies.

**Comment by alexschneider** [comment]
Agreed.

**Comment by alexschneider** [comment]
If this test passes travis, should be good to merge.

**Comment by rachelriv** [comment]
Just added shrinkwrap

**Comment by alexschneider** [comment]
@rachelriv it looks like shrinkwrap only wrapped the dependencies, not the dev dependencies. Is that possible with npm shrinkwrap?

**Comment by rachelriv** [comment]
`npm shrinkwrap --dev`

I just added the dev dependencies.

**Comment by rachelriv** [comment]
LGTM :tea:

**Comment by alexschneider** [comment]
LGTM :tea:

**Pull request merged**
